/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.app2;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import com.eomcs.app2.table.ScoreTable;
import com.eomcs.app2.vo.Score;

public class ServerApp {

  ScoreTable scoreHandler = new ScoreTable();

  public static void main(String[] args) {
    new ServerApp().service();
  }

  public void service() {
    try {
      ServerSocket serverSocket = new Serversocket(3306);

      while (true) {
        Socket socket = serverSocket.accept();
        ObjectInputStream in = new ObjectInputStream(socket.getInputStream());  // ObjectInputStream : 객체를 입출력할 수 있는 데코
        ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());

        while (true) {
          String command = in.readUTF();
          if (command.equals("quit")) {
            break;
          }

          try {
            switch (command) {
              case "insert":
                Score score = (Score) in.readObject();
                int count = ScoreTable.insert((Score) in.readObject());
                out.writeUTF("success");
                out.writeInt(count);
                break;
              case "selectList":
                Score[] scores = ScoreTable.selectList();
                out.writeUTF("success");
                out.writeObject(scores);
                break;
              case "selectOne":
                int no = in.readInt();
                score = ScoreTable.selectOne(no);
                out.writeUTF("success");
                out.writeObject(score);
                break;
              case "update":
                int no = in.readInt();
                score = (Score) in.readObject();
                count = ScoreTable.update(no, score);
                out.writeUTF("success");
                out.writeInt(count);
                break;
              case "delete":
                no = in.readInt();
                count = ScoreTable.delete(no);
                out.writeUTF("success");
                out.writeInt(count);
                break;
              default:
                out.writeUTF("faile");
                out.writeUTF("해당 명령을 지원하지 않습니다");
            }
            out.flush();
          } catch(Exception e) {
            out.writeUTF("faile");
            out.writeUTF("실행 오류: " + e.getMessage());
            out.flush();
          }
        }
      }
    } catch(Exception e) {
      System.out.println("서버 실행 오류!");
    }
    System.out.println("종료!");
  }

}
